[package]
name = "innoDelivery_userService"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-httpauth = { git = "https://github.com/actix/actix-web-httpauth" }
chrono = { version = "0.4.10", features = ["serde"] }
derive_more = "0.99.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
diesel = { version = "2.0.2", features = ["postgres", "r2d2", "chrono", "uuid"] }
postgres = "0.19.4"
eyre = "0.6.8"
color-eyre = "0.6.2"
futures = { version = "0.3.1", features = ["compat"] }
r2d2 = "0.8.8"
actix-identity = "0.4.0"
#uuidv07 = { version = "1.2.2", optional = true, package = "uuid"}
uuid = { version = "1.2.2", features = ["serde"] }
jsonwebtoken = "8.2.0"
tracing = "0.1.19"
tracing-futures = "0.2.4"
tracing-log = { version = "0.1.1", features = ["env_logger"] }
serde_with = "2.1.0"
serde_derive = "1.0.151"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
log = "0.4.17"
actix-rt = "2.7.0"
dotenv = "0.15.0"
argonautica = "0.2.0"
