[package]
name = "innoDelivery_userService"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2.7.0"
actix-web-httpauth = { git = "https://github.com/actix/actix-web-httpauth" }
chrono = { version = "0.4.10", features = ["serde"] }
derive_more = "0.99.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.0.2", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15.0"
env_logger = "0.10.0"
postgres = "0.19.4"
futures = "0.3.1"
r2d2 = "0.8.8"
actix-identity = "0.5.2"
uuid = {version = "1.2.2", features = ["v4"] }
#jsonwebtoken = "8.2.0"
